# Generated by Django 5.2.6 on 2025-09-19 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_rental', '0004_seed_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('unread', 'Chưa đọc'), ('read', 'Đã đọc'), ('replied', 'Đã trả lời')], default='unread', max_length=20),
        ),
        migrations.CreateModel(
            name='ViewingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('alternative_date', models.DateField(blank=True, null=True)),
                ('alternative_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Hoàn thành')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('landlord_response', models.TextField(blank=True)),
                ('confirmed_date', models.DateField(blank=True, null=True)),
                ('confirmed_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_schedules', to='apartment_rental.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
