# Generated by Django 5.2.6 on 2025-09-21 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_rental', '0005_contact_status_viewingschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='deposit_status',
            field=models.CharField(choices=[('none', 'Không đặt cọc'), ('pending', 'Đang chờ thanh toán cọc'), ('paid', 'Đã đặt cọc'), ('failed', 'Thanh toán thất bại'), ('refunded', 'Đã hoàn cọc')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('provider', models.CharField(default='vnpay', max_length=30)),
                ('vnp_TxnRef', models.CharField(max_length=64, unique=True)),
                ('vnp_OrderInfo', models.CharField(blank=True, max_length=255, null=True)),
                ('vnp_TransactionNo', models.CharField(blank=True, max_length=64, null=True)),
                ('vnp_ResponseCode', models.CharField(blank=True, max_length=10, null=True)),
                ('vnp_BankCode', models.CharField(blank=True, max_length=50, null=True)),
                ('vnp_PayDate', models.CharField(blank=True, max_length=14, null=True)),
                ('vnp_SecureHash', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('success', 'Thành công'), ('failed', 'Thất bại')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apartment_rental.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
